### ISSUE TITLE
Bug: Possible to return arrays from functions

### ISSUE THREAD

**Issue by PresscotCoats** [nitros12/A-Compiler#4]
Hi, when writing programs and compiling with this compiler, I have found that it is possible to declare functions returning arrays.
For example:

```
fn a() -> [u1@4] {
	return {1, 2, 3, 4};
}

fn main() {
	var x := a();

	std.printf("%u1 %u1 %u1 %u1\n", x[0], x[1], x[2], x[3]);
}
```
This appears to function, presumably because the size of the array `1 * 4` fits into a register size.

However, the following:

```
fn a() -> [u1@5] {
	return {1, 2, 3, 4};
}

fn main() {
	var x := a();

	std.printf("%u1 %u1 %u1 %u1\n", x[0], x[1], x[2], x[3]);
}
```
(Note the array size changed to 5)

Produces an assertion exception:

```py
~/dev/wewcompiler/objects/base.py", line 551, in get_register
    assert size in (1, 2, 4, 8)
AssertionError
```

After looking through your code it seems like the best place to apply a fix would be here:

https://github.com/nitros12/A-Compiler/blob/61783d3072015927b38e8293e2a0a3333c017229/wewcompiler/objects/types.py#L198-L200

**Comment by nitros12** [comment]
Fixed in a4174bd0b4602f34c0f0f13968a18260092eb2a6

Test case added:
```py
@for_feature(functions="Functions")
def test_function_array_return():
    """Make sure we can't return arrays from functions."""
    decl = """
    fn test() -> [u1@4] {
        return {1, 2, 3, 4};
    }
    """

    with raises(CompileException):
        compile(decl)
```

Correctly fails with:
```
Functions cannot return array types.
On line 1:
  1| fn a() -> [u1@5] {
               ^----^
  2|     return {1, 2, 3, 4};
  3| }
  4|
  5| fn main() {
  6|     var x := a();
```
